version: '3.9'

services:
  db:
    image: sakiladb/mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_USER: sakila
      MYSQL_PASSWORD: p_ssW0rd
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - 3307:3306

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: quarkus-sakila-ashim:latest
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db:3306/sakila
      QUARKUS_DATASOURCE_USERNAME: sakila
      QUARKUS_DATASOURCE_PASSWORD: p_ssW0rd
    ports:
      - 8081:8080
    command: ["java", "-jar", "/app/quarkus-app/quarkus-run.jar"]